language: ruby
rvm:
- 2.3.3

jobs:
  include:
    - stage: build
      script:
      - npm install
      - bundle
      - bundle exec jekyll build
    - stage: test
      script: bundle exec htmlproofer ./_site --http-status-ignore "999"
    - stage: deploy
      script:
      - chmod +x ./cideploy.sh
      - ./cideploy.sh

branches:
  only:
  - development

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
