language: ruby
rvm:
- 2.3.3

script:
- bundle exec jekyll build
- bundle exec htmlproofer ./_site --http-status-ignore "999"

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true